Repository planetarium/patrol-reward-service, pull requests merged in 2023-11, with the labels that each got.

#18 ⬆️ bump: lib9c
  PatrolRewardService/PatrolRewardService/PatrolRewardService.csproj
Labels: Extra Small

#19 hotfix tx result
  PatrolRewardService/PatrolRewardService/GraphqlTypes/NineChroniclesClient.cs
  PatrolRewardService/PatrolRewardService/TransactionWorker.cs
Labels: Extra Small

#20 Fix replaced tx stage not work
  PatrolRewardService/PatrolRewardService/ContextService.cs
  PatrolRewardService/PatrolRewardService/TransactionWorker.cs
Labels: Extra Small

#22 Add invalid tx count query for monitoring
  PatrolRewardService/PatrolRewardService.Tests/QueryTypeTest.cs
  PatrolRewardService/PatrolRewardService/ContextService.cs
  PatrolRewardService/PatrolRewardService/GraphqlTypes/QueryType.cs
  PatrolRewardService/PatrolRewardService/Query.cs
  PatrolRewardService/PatrolRewardService/TransactionStageWorker.cs
  PatrolRewardService/PatrolRewardService/TransactionWorker.cs
Labels: Medium

#23 Missing test snapshot
  PatrolRewardService/PatrolRewardService.Tests/__snapshots__/QueryTypeTest.InvalidTxCount.snap
Labels: No Changes

#24 Fix service
  PatrolRewardService/PatrolRewardService.Tests/Fixtures.cs
  PatrolRewardService/PatrolRewardService/ContextService.cs
  PatrolRewardService/PatrolRewardService/GraphqlTypes/MutationType.cs
  PatrolRewardService/PatrolRewardService/Mutation.cs
  PatrolRewardService/PatrolRewardService/TransactionStageWorker.cs
  PatrolRewardService/PatrolRewardService/TransactionWorker.cs
  PatrolRewardService/PatrolRewardService/appsettings.json
Labels: Small
